source:
  dir: "/home/jdoe/Downloads"
  regex: "^.+\.(mkv|avi)$"

default_dest_dir: "#{dir}/Season #{m[1].to_i}/"

dirs:
  tv_shows: "/mnt/storage/Video/TV shows"

mappings:
  -
    regex: \/?([^\/]+)\.s(\d\d)e\d\d
    dest_dir: "#{@dirs['tv_shows']}/#{m[1].split('.').each.collect { |x| x.capitalize }.join(' ')}/Season #{m[2].to_i}/"
