source:
  dir: "/tmp/source_dir"
  regex: ^.+\.mp3$
destination:
  dir: "#{dir}"
mappings:
  - pearl_jam:
    label: "All Pearl Jam music"
    regex: ^pearl\.jam.\+\.mp3$
    dir: "/storage/Pearl Jam"
